### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by sudoplox** [Aniket-Pradhan/lsd#2]
Thanks

**Comment by Aniket-Pradhan** [comment]
No shit-talk here. :)

I was thinking of adding a GIF in the comments. Will do that soon.

If you want to contribute in that, refer [here](https://help.github.com/articles/creating-a-pull-request/).

**Comment by pranaay** [comment]
plese assign to me

**Comment by Aniket-Pradhan** [comment]
> plese assign to me

Send a PR. :3
